[project]
name = "llama-tuna"
version = "0.0.1"
description = "Local LLM inference optimizer for llama.cpp."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "tqdm>=4.68.3",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project.scripts]
llama-tuna = "llama_tuna.main:main"
